[14-Mar-2021 19:50:17 Europe/Berlin] Uncaught exception: 'PDOException' with message ' SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)'
Stack trace: #0 C:\xampp\htdocs\feedback\Core\Model.php(20): PDO->__construct('mysql:host=loca...', 'root', 'root')
#1 C:\xampp\htdocs\feedback\App\Controllers\Messages.php(21): Core\Model::getDB()
#2 [internal function]: App\Controllers\Messages->addAction()
#3 C:\xampp\htdocs\feedback\Core\Controller.php(22): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\feedback\Core\Router.php(72): Core\Controller->__call('add', Array)
#5 C:\xampp\htdocs\feedback\public\index.php(20): Core\Router->dispatch('messages/add')
#6 {main}
Thrown inC:\xampp\htdocs\feedback\Core\Model.php on line 20
